// Date: 29/03/2013 17:28:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.themike.modjam.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelCarvingStone extends ModelBase {

  static ModelRenderer Shape1;
  
  public ModelCarvingStone() {
    textureWidth = 64;
    textureHeight = 64;
    
    Shape1 = new ModelRenderer(this, 0, 0);
    Shape1.addBox(0F, 0F, 0F, 14, 14, 14);
    Shape1.setRotationPoint(-7F, 10F, -7F);
    Shape1.setTextureSize(64, 64);
    Shape1.mirror = true;
    setRotation(Shape1, 0F, 0F, 0F);
  }
  
  public static void render(float f5) {
    Shape1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}